apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: richardmemory/nodeapihello:1.1
        ports:
        - containerPort: 3000